[package]
name = "picot-rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "piclib"
path = "src/lib.rs"

[[bin]]
name = "picot"
path = "src/main.rs"

[dependencies]
cortex-m = "0.7.3"
cortex-m-rt = "0.7.1"
alloc-cortex-m = "0.4.1"
rp2040-boot2 = "0.2.0"

pico_explorer = { git = "https://github.com/rp-rs/rp-hal.git", branch = "main" }
pio = "0.1.0"

embedded-hal = "0.2.6"
embedded-time = "0.12.1"
embedded-graphics = "0.7.1"
display-interface = "0.4.1"

cortex-m-semihosting = "0.3.7"
panic-semihosting = "0.5.6"

nb = "1.0.0"
arrayvec = { version = "0.7.2", default-features = false }
heapless = "0.7.9"
num-traits = { version = "0.2.14", default-features = false, features = [ "libm" ] }
rand = { version = "0.8.4", default-features = false, features = [ "small_rng" ] }
palette = { version = "0.6.0", default-features = false, features = [ "libm" ] }
smart-leds-trait = "0.2.1"
self_cell = "0.10.2"
fixed = "1.11.0"
cordic = "0.1.5"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
